name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Étape 4 : Configurer PostgreSQL
      - name: Set up PostgreSQL
        uses: Harmon758/postgresql-action@v2.0.0
        with:
          postgresql version: '14'
          postgresql db: pipeline_db
          postgresql user: postgres
          postgresql password: Poiuytrezaqsd09!21

      # Étape 5 : Exécuter les tests
      - name: Run tests
        run: pytest tests/
        